In [ ]:
# Exercise A

A = np.array([
    [10, 25, 40],
    [55, 70, 85],
    [15, 35, 95]
])

print('Array A:')
print(A)

print('\nA.shape')
print(A.shape)


print('\nA.max():')
print(A.max())

print('\nnp.max(A):')
print(np.max(A))



Array A:
[[10 25 40]
 [55 70 85]
 [15 35 95]]

A.shape
(3, 3)

A.max():
95

np.max(A):
95


In [ ]:
# Exercise B

import numpy as np

array_ones = np.ones((5, 5), dtype = int)

print('5x5 Array:')
print(array_ones)

print('\nShape:')
print(array_ones.shape)

print('\nSize:')
print(array_ones.size)

print('\nNumber of Dimensions:')
print(array_ones.ndim)

5x5 Array:
[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]

Shape:
(5, 5)

Size:
25

Number of Dimensions:
2


In [7]:
# EXERCISE C:

import numpy as np

numbers = np.arange(-5, 6)
result = numbers*2

print('Original Array:')
print(numbers)

print('\nResult Array:')
print(result)

Original Array:
[-5 -4 -3 -2 -1  0  1  2  3  4  5]

Result Array:
[-10  -8  -6  -4  -2   0   2   4   6   8  10]
